# Generated by Django 5.1.6 on 2026-03-25 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_remove_product_owner_product_allergen_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.producer'),
            preserve_default=False,
        ),
    ]
