from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import (
    HomeView,
    ProducerContentCreateView,
    ProducerContentDeleteView,
    ProducerContentListView,
    ProducerContentUpdateView,
    ProducerDashboardView,
    ProducerLoginView,
    ProducerOrderDetailView,
    ProducerOrderItemUpdateView,
    ProducerOrderListView,
    ProducerProfileUpdateView,
    ProducerRegisterView,
    ProducerSettlementDetailView,
    ProducerSettlementListView,
    ProducerSurplusCreateView,
    ProducerSurplusDeleteView,
    ProducerSurplusListView,
    ProducerSurplusUpdateView,
    ProductCreateView,
    ProductDeleteView,
    ProductListView,
    ProductUpdateView,
)

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("producer/dashboard/", ProducerDashboardView.as_view(), name="dashboard"),
    path("producer/login/", ProducerLoginView.as_view(), name="producer-login"),
    path("producer/logout/", LogoutView.as_view(next_page="core:home"), name="producer-logout"),
    path("producer/register/", ProducerRegisterView.as_view(), name="producer-register"),
    path("producer/profile/", ProducerProfileUpdateView.as_view(), name="producer-profile"),
    path("producer/products/", ProductListView.as_view(), name="product-list"),
    path("producer/products/new/", ProductCreateView.as_view(), name="product-create"),
    path("producer/products/<int:pk>/edit/", ProductUpdateView.as_view(), name="product-update"),
    path("producer/products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product-delete"),
    path("producer/orders/", ProducerOrderListView.as_view(), name="order-list"),
    path("producer/orders/<int:pk>/", ProducerOrderDetailView.as_view(), name="order-detail"),
    path("producer/order-items/<int:pk>/", ProducerOrderItemUpdateView.as_view(), name="order-item-update"),
    path("producer/settlements/", ProducerSettlementListView.as_view(), name="settlement-list"),
    path("producer/settlements/<int:pk>/", ProducerSettlementDetailView.as_view(), name="settlement-detail"),
    path("producer/surplus/", ProducerSurplusListView.as_view(), name="surplus-list"),
    path("producer/surplus/new/", ProducerSurplusCreateView.as_view(), name="surplus-create"),
    path("producer/surplus/<int:pk>/edit/", ProducerSurplusUpdateView.as_view(), name="surplus-update"),
    path("producer/surplus/<int:pk>/delete/", ProducerSurplusDeleteView.as_view(), name="surplus-delete"),
    path("producer/content/", ProducerContentListView.as_view(), name="content-list"),
    path("producer/content/new/", ProducerContentCreateView.as_view(), name="content-create"),
    path("producer/content/<int:pk>/edit/", ProducerContentUpdateView.as_view(), name="content-update"),
    path("producer/content/<int:pk>/delete/", ProducerContentDeleteView.as_view(), name="content-delete"),
]
